### ISSUE TITLE
XML tags in JSON.

### ISSUE THREAD

**Issue by Midnoclose** [crhallberg/json-against-humanity#11]
I noticed that there were xml/html tags in one of the entries : `<i>(Heavy breathing)</i><br>Luke, I am _.`.
This is not suitable for the application I am making.

**Comment by crhallberg** [comment]
Sorry to hear that! This was done to attempt to get closer to the formatting of the cards. You can try the [markdown versions](https://github.com/crhallberg/json-against-humanity/blob/cb59e60da98db06aaa9121b449c024a71565f852/src/PAXE2014/black.md.txt#L1) to see if that would suit your case.

If you have to strip the tags out to work with your application, feel free to contribute that back!
