### ISSUE TITLE
Adding the Black Friday 2019 cards

### ISSUE THREAD

**Issue by TomJansen** [crhallberg/json-against-humanity#19]
Hi! I have typed out the Black Friday 2019 cards (both the AI generated and human card packs). Now I want to add these but how should I do that? Given that they are basically 2 packs. They both have a different logo in the corner, so I would guess adding them as 2 separate packs?

**Comment by crhallberg** [comment]
Thank you for your potential contribution! If you haven't seen the [contribution guide](https://github.com/crhallberg/json-against-humanity/blob/master/CONTRIBUTING.md), that would be a good place to start. I'll be here if you have any more questions!

**Comment by TomJansen** [comment]
See #20
