### ISSUE TITLE
Add Design Pack

### ISSUE THREAD

**Issue by crhallberg** [crhallberg/json-against-humanity#2]
This would require supporting images on cards

- [ ] Support images
- [ ] Source Design Pack
- [ ] Add Design Pack
- [ ] Source Hawaii 2 card
- [ ] Add Hawaii 2 card (in appropriate Christmas pack)

**Comment by TomJansen** [comment]
Includes the Sean Connery picture from the Sci-Fi pack
Source image: http://web.archive.org/web/20200523140215if_/https://i.pinimg.com/originals/e4/4d/58/e44d582845cb3d96ee4124051a3ed9df.jpg

Image of card: http://web.archive.org/web/20200523140430if_/https://i.redd.it/pq5ko8pkp1141.jpg

A solution would be to base64 encode them. This way you can still "save" them as text

**Comment by TomJansen** [comment]
Source for design pack: https://kyletfujita.com/2015/08/02/cards-against-humanity-design-pack-full-spoiler/2/

**Comment by TomJansen** [comment]
Source sloth card: https://www.flickr.com/photos/28759204@N00/4801982766/ (I believe)
