### ISSUE TITLE
Black Card Draw/Pick information not included

### ISSUE THREAD

**Issue by ipmcc** [crhallberg/json-against-humanity#27]
Some black cards in the game require the player to draw more cards prior to playing. A classic example is the "Make a Haiku." card from the Base deck which tells the player to draw 2 more cards, and then pick 3 cards to form their Haiku. This info appears to be missing from this repository.

Any plans to add this? FWIW, this info is captured in the Pretend You're Xyzzy database (obviously only for the card sets contained there).

For example:
![Haiku-Card-1-222x300](https://user-images.githubusercontent.com/537077/91567925-420cb180-e913-11ea-9161-1824b8e88e59.jpg)

**Comment by crhallberg** [comment]
I'm sorry that the documentation doesn't make this clear but the compact and full JSON files both include pick information in the following format: 

```JSON
{
  "text": "I love bacon as much as _ loves _.", 
  "pick": 2
}
```

All CAH cards draw one less than they require so Draw 1, Pick 2 and Draw 2, Pick 3. I hope this helps!

**Comment by ipmcc** [comment]
I didn't realize that `draw == pick - 1` was rigorously true. Thanks!
