### ISSUE TITLE
Compact download pulls cards from the wrong packs

### ISSUE THREAD

**Issue by Sierraffinity** [crhallberg/json-against-humanity#35]
Downloading an assortment of cards in compact form grabs the pack associated with the display order index instead of internal order index. In the `download-compact` click function, the metadata is grabbed from `PACKLIST` which is sorted by display order, while card data is grabbed from deck.getPacks, which is in the order in which the cards were hydrated from the original JSON.

**Comment by crhallberg** [comment]
Thank you! I finally was able to track this down with your help! Fixes pushed here (08e1f9637a51480dcb39df84d5ea1b8fff6b2f65) and am uploading to the site now!
