### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by yanniboi** [crhallberg/json-against-humanity#44]
I've reached out directly to CAH as well, however I thought I'd ask here as well.

I am planning to create a commercial game and have a CAH DLC. The game itself will be unrelated and the CAH expansion would be free (and potentially open sourced to comply with the licensing requirement), but I have no idea if this will be enough to comply with the requirements, since most of the logic of the project will be in the closed base package.

Any guidance on the subject would be very much appreciated.

**Comment by crhallberg** [comment]
Hello, @yanniboi! My understanding of CAH's licensing is that the [Creative Commons license](https://creativecommons.org/licenses/by-nc-sa/4.0/) they've chosen for their writing would prevent you from having CAH's cards and prompts in your **commercial** game. Creating a game based on the gameplay is *probably* alright (I am not a lawyer) but the use of CAH's name, logo, or writing would require permission and likely for the license to apply to the whole project.

Their website used to put it more clearly (emphasis mine):

> We give you permission to use the Cards Against Humanity® writing under a limited Creative Commons BY-NC-SA 4.0 license. That means you can use our **writing** if (and only if) you do all of these things:
> 1. Make your work available totally for free.
> 2. Share your work with others under the same Creative Commons license that we use.
> 3. Give us credit in your project.

This elegantly breaks down the three clauses of their chosen license, [CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/), which applies to their graphic design, name, slogans, logos, and all card text.

1. Free = Non-Commercial (NC)
2. Use the same license = Share-Alike (SA)
3. Give credit = Attribution (BY).

As for the unofficial cards in this collection, if they are considered [to "transform" or to "build upon" CAH's material](https://creativecommons.org/licenses/by-nc-sa/4.0/#terms), they would be required to share the content of those cards under the same license (Share-Alike), running you into the same issues. Some have gone on to sell commercial copies which may cause additional licensing issues, but I'm not knowledgeable enough in the law to know where the line is drawn. Hopefully your email to CAH will clear things up!

As a final note from the [FAQ on the current CAH homepage](https://www.cardsagainsthumanity.com/#faq-list) (word "graphic" added from the [2020 version of their website](http://web.archive.org/web/20201231201938/https://cardsagainsthumanity.com/)):

> Can I sell my own Cards Against Humanity thing?
>
> No! We legally own the name "Cards Against Humanity" as well as the [graphic] design of our game, the slogan, our logos, and all of our writing. That means you need a license from us to use any of that stuff. Please don't make anything that confuses people into thinking it’s affiliated with us, or we’ll have to call the lawyers.

Best,
Chris

**Comment by yanniboi** [comment]
Thank for you detailed and prompt response! That's very helpful.

All the best 👍
