### ISSUE TITLE
White/black object parity for JSON

### ISSUE THREAD

**Issue by teddybradford** [crhallberg/json-against-humanity#5]
It would be nice to have the structure of the white and black card arrays be the same. i.e., instead of white cards being an array of strings, have it be an array of objects, each with a "text" property, just like the black cards.

This would make using the data much easier as the structure would be consistent between the two types of cards.

**Comment by crhallberg** [comment]
That makes sense. Is there any other info besides text and pick that we should add to the cards?

**Comment by crhallberg** [comment]
Would it also make sense to add a format that is just two arrays of all the card with their own data attached? The current format is geared towards a small file size, but that may not be the most useful restraint.

**Comment by teddybradford** [comment]
What are you thinking the structure would look like?

**Comment by crhallberg** [comment]
```JS
{
  "black": [
    {
      "text":,
      "pick":,
      "symbol":,
      "deck": "deck1"
     },
     // ...
  ],
  "white": [
    {
      "text":,
      "symbol":,
      "deck": "deck2"
     },
     // ...
  ],
  "metadata": {
    "deck1": {
      "name": "Battle Deck 2K17",
      "description": "..."
    },
    "deck2": {},
  }
}
```

**Comment by teddybradford** [comment]
That looks good to me. You might also consider changing "black" to "prompts" and "white" to "responses" (ref: https://docs.google.com/spreadsheets/d/1lsy7lIwBe-DWOi2PALZPf5DgXHx9MEvKfRw1GaWQkzg/edit#gid=59).

**Comment by crhallberg** [comment]
I'm only mildly opposed to this, it wouldn't be any more technically difficult, but I feel like the association is really strong.

**Comment by teddybradford** [comment]
I'm fine with it either way. I only brought it up because this database includes lots of unofficial decks, which technically aren't supposed to use the names "black" and "white" according to CAH.
